export const netherlandsCities = [
    { value: 'amsterdam', label: 'Amsterdam' },
    { value: 'rotterdam', label: 'Rotterdam' },
    { value: 'the-hague', label: 'The Hague' },
    { value: 'utrecht', label: 'Utrecht' },
    { value: 'eindhoven', label: 'Eindhoven' },
    { value: 'tilburg', label: 'Tilburg' },
    { value: 'groningen', label: 'Groningen' },
    { value: 'almere', label: 'Almere' },
    { value: 'breda', label: 'Breda' },
    { value: 'nijmegen', label: 'Nijmegen' },
    { value: 'enschede', label: 'Enschede' },
    { value: 'haarlem', label: 'Haarlem' },
    { value: 'arnhem', label: 'Arnhem' },
    { value: 'zaanstad', label: 'Zaanstad' },
    { value: 'amersfoort', label: 'Amersfoort' },
    { value: 'haarlemmermeer', label: 'Haarlemmermeer' },
    { value: 'apeldoorn', label: 'Apeldoorn' },
    { value: 's-hertogenbosch', label: "'s-Hertogenbosch" },
    { value: 'hoorn', label: 'Hoorn' },
    { value: 'maastricht', label: 'Maastricht' },
    { value: 'leiden', label: 'Leiden' },
    { value: 'dordrecht', label: 'Dordrecht' },
    { value: 'zoetermeer', label: 'Zoetermeer' },
    { value: 'zwolle', label: 'Zwolle' },
    { value: 'deventer', label: 'Deventer' },
    { value: 'leeuwarden', label: 'Leeuwarden' },
    { value: 'venlo', label: 'Venlo' },
    { value: 'delft', label: 'Delft' },
    { value: 'sittard-geleen', label: 'Sittard-Geleen' },
    { value: 'helmond', label: 'Helmond' },
    { value: 'hilversum', label: 'Hilversum' },
    { value: 'roermond', label: 'Roermond' },
    { value: 'middelburg', label: 'Middelburg' },
    { value: 'weert', label: 'Weert' },
    { value: 'others', label: 'others' },
  ];