export const netherlandsCities = [
  { value: 'Alkmaar', label: 'Alkmaar' },
  { value: 'Almere', label: 'Almere' },
  { value: 'Almelo', label: 'Almelo' },
  { value: 'Alphen-aan-den-Rijn', label: 'Alphen aan den Rijn' },
  { value: 'Amersfoort', label: 'Amersfoort' },
  { value: 'Amsterdam', label: 'Amsterdam' },
  { value: 'Apeldoorn', label: 'Apeldoorn' },
  { value: 'Arnhem', label: 'Arnhem' },
  { value: 'Assen', label: 'Assen' },
  { value: 'Breda', label: 'Breda' },
  { value: 'Capelle-aan-den-IJssel', label: 'Capelle aan den IJssel' },
  { value: 'Delft', label: 'Delft' },
  { value: 'Deventer', label: 'Deventer' },
  { value: 'Dordrecht', label: 'Dordrecht' },
  { value: 'Eindhoven', label: 'Eindhoven' },
  { value: 'Emmen', label: 'Emmen' },
  { value: 'Enschede', label: 'Enschede' },
  { value: 'Groningen', label: 'Groningen' },
  { value: 'Haarlem', label: 'Haarlem' },
  { value: 'Haarlemmermeer', label: 'Haarlemmermeer' },
  { value: 'Helmond', label: 'Helmond' },
  { value: 'Hengelo', label: 'Hengelo' },
  { value: 'Hilversum', label: 'Hilversum' },
  { value: 'Hoorn', label: 'Hoorn' },
  { value: 'Leeuwarden', label: 'Leeuwarden' },
  { value: 'Leiden', label: 'Leiden' },
  { value: 'Lelystad', label: 'Lelystad' },
  { value: 'Maastricht', label: 'Maastricht' },
  { value: 'Middelburg', label: 'Middelburg' },
  { value: 'Nijmegen', label: 'Nijmegen' },
  { value: 'Oss', label: 'Oss' },
  { value: 'Purmerend', label: 'Purmerend' },
  { value: 'Roermond', label: 'Roermond' },
  { value: 'Rotterdam', label: 'Rotterdam' },
  { value: 'S-Hertogenbosch', label: "'s-Hertogenbosch" },
  { value: 'Schiedam', label: 'Schiedam' },
  { value: 'Sittard-Geleen', label: 'Sittard-Geleen' },
  { value: 'Spijkenisse', label: 'Spijkenisse' },
  { value: 'The-Hague', label: 'The Hague' },
  { value: 'Tilburg', label: 'Tilburg' },
  { value: 'Utrecht', label: 'Utrecht' },
  { value: 'Venlo', label: 'Venlo' },
  { value: 'Vlaardingen', label: 'Vlaardingen' },
  { value: 'Weert', label: 'Weert' },
  { value: 'Zaandam', label: 'Zaandam' },
  { value: 'Zaanstad', label: 'Zaanstad' },
  { value: 'Zeist', label: 'Zeist' },
  { value: 'Zoetermeer', label: 'Zoetermeer' },
  { value: 'Zwolle', label: 'Zwolle' },
  { value: 'Others', label: 'Others' },
];
